name:
  model_name: "yolov_11"

model:
  name: yolo11n
  experiment: development

data_count: 
  old: Palm Tree Label 200m Splitted.v7i.yolov11
  root: data_count
  sampling: sampling
  train_path: train
  test_path: test
  valid_path: valid
  num_classes: 1
  names: Palm-Tree
  yaml: data.yaml

data_classify: 
  old: Apple Detection.v2i.yolov11
  root: data_classify
  sampling: sampling_classify
  train_path: train
  test_path: test
  valid_path: valid
  num_classes: 1
  names: Apples
  yaml: data_classify.yaml

output:
  root: output
  clean: clean
  model: model

train:
  test_size: 0.2
  random_state: 42
  shuffle: true
  batch_size: 8
  num_workers: 4
  max_epochs: 128

preprocessing:
  resize_img: 640

