name:
  model_name: "yolo_v10"

model:
  name: yolov10n
  experiment: development

data: 
  root: data
  sampling: sampling
  train_path: train
  test_path: test
  valid_path: valid
  num_classes: 1
  names: Palm-Tree

output:
  root: output
  clean: clean
  model: model

train:
  test_size: 0.2
  random_state: 42
  shuffle: true
  batch_size: 8
  num_workers: 4
  max_epochs: 512

preprocessing:
  resize_img: 640

