artifact_uri: /Users/sadewawicak/Researchs/Dinusantara/palm.dinusantara/runs/mlflow/263221287858218345/d76ab4cd9e3d45aba9fcdc02baae7e20/artifacts
end_time: 1736078217360
entry_point_name: ''
experiment_id: '263221287858218345'
lifecycle_stage: active
run_id: d76ab4cd9e3d45aba9fcdc02baae7e20
run_name: '20250105_164322'
run_uuid: d76ab4cd9e3d45aba9fcdc02baae7e20
source_name: ''
source_type: 4
source_version: ''
start_time: 1736070304474
status: 3
tags: []
user_id: msiin
