artifact_location: /Users/sadewawicak/Researchs/Dinusantara/palm.dinusantara/runs/mlflow/0
creation_time: 1736063272732
experiment_id: '0'
last_update_time: 1736063272732
lifecycle_stage: active
name: Default
